### ISSUE TITLE
Deploy failure may be due to latest gcloud version of gsutil having incomplete libraries

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/npad-support#37]
A recent build failed to deploy due to a failure of gsutil.

```
+gcloud version
Google Cloud SDK 160.0.0
bq 2.0.24
core 2017.06.16
gcloud 
gsutil 4.26

...

+gsutil cp slicebase-i386/i686/iupui_npad-master-201706231108.mlab.i686.rpm gs://legacy-rpms-mlab-staging/testing/
Traceback (most recent call last):
  File "/home/travis/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/home/travis/google-cloud-sdk/platform/gsutil/gsutil.py", line 113, in RunMain
    import gslib.__main__
  File "/home/travis/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 39, in <module>
    import boto
  File "/home/travis/google-cloud-sdk/platform/gsutil/third_party/boto/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/home/travis/google-cloud-sdk/platform/gsutil/third_party/boto/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/home/travis/google-cloud-sdk/platform/gsutil/third_party/boto/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python2.7/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ImportError: No module named google_compute_engine
Script failed with status 1
```

**Comment by stephen-soltesz** [comment]
Upstream bug: https://github.com/GoogleCloudPlatform/compute-image-packages/issues/262

`gsutil` now requires the `google-compute-engine` python package.

**Comment by critzo** [comment]
resolved
